### ISSUE TITLE
Getting blank screen on IE browser while trying to access Demo 

### ISSUE THREAD

**Issue by Suryanarayana-2018** [cheekujha/react-table-filter#10]
I am unable to see the content (getting a blank screen) of demo https://cheekujha.github.io/react-table-filter/ for IE browser where I checked with versions 10 and 11. I have added the screen shots of the same below. Can you please let me know how to fix this? Is there any configuration or settings for IE (It works fine in Chrome and Edge browsers) or any limitation for IE? Awaiting for your reply on this ASAP.
[react-table-filter-IE.docx](https://github.com/cheekujha/react-table-filter/files/1994011/react-table-filter-IE.docx)

**Comment by cheekujha** [comment]
Hey can you please also mention what windows version are you using. I checked in windows 10 , edge, ie 10-11, it seems to work fine. 

Majorly what i can see from screenshots is that **Object.assign** and **Set** methods are not supported for browser you are testing and will need polyfills for the same

**Comment by Suryanarayana-2018** [comment]
Hi, I am using windows 10 OS. But It's not worked even after adding polyfill unless i changed the utils.js as shown below:
export const isTypeArray = (val) => {
	var toString = Object.prototype.toString;  //for IE and Firefox**
	return toString.call(val) === "[object Array]" ? true : false;
}

export const isTypeString = (val) => {
	var toString = Object.prototype.toString; //for IE and Firefox**
	return toString.call(val) === "[object String]" ? true : false;
}
it got fixed.

**Comment by Suryanarayana-2018** [comment]
Thanks for your support.

**Comment by nehalsanghvi** [comment]
Hi 
The warning is coming from the <th> child element 
react-table-filter/src/template.js:line 38/49 can please check if we can add key={} for map array of elements. 
Below are the screenshot with your examples
<img width="1111" alt="screen shot 2018-08-08 at 2 57 52 pm" src="https://user-images.githubusercontent.com/40773231/43866852-109b5dfa-9b1c-11e8-858f-4bad66529cec.png">
<img width="79" alt="screen shot 2018-08-08 at 2 58 15 pm" src="https://user-images.githubusercontent.com/40773231/43866853-10bdab30-9b1c-11e8-8fdd-61c835c65e7a.png">
<img width="694" alt="screen shot 2018-08-08 at 2 58 18 pm" src="https://user-images.githubusercontent.com/40773231/43866854-10d81970-9b1c-11e8-8a63-5d8607662387.png">
<img width="418" alt="screen shot 2018-08-08 at 2 58 32 pm" src="https://user-images.githubusercontent.com/40773231/43866855-10f46aee-9b1c-11e8-805a-30fcbd450e0e.png">
