### ISSUE TITLE
Not working in IE 11.12 version and warning in all browers

### ISSUE THREAD

**Issue by nehalsanghvi** [cheekujha/react-table-filter#12]
HTML1300: Navigation occurred.
react-table-filter
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
react-table-filter
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <tbody>. See https://fb.me/react-warning-keys for more information.
    in tr
    in Unknown
--_applyInitialFilters- [object Object]
   "--_applyInitialFilters-"
   {
      [functions]: ,
      __proto__: { }
   }
BELOW Error in IE Only
The above error occurred in one of your React components:
    in Unknown
    in thead
    in table
    in div
    in div
    in div
    in Unknown

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries.
SCRIPT65535: Invalid calling object
bundle.js (430,2)
SCRIPT65535: Invalid calling object
bundle.js (8133,25)

**Comment by LTPrashant** [comment]
Can you check if this issue helps you [Link](https://github.com/cheekujha/react-table-filter/issues/10)

**Comment by LTPrashant** [comment]
Updated util.js in version 1.1.2 try that. If it is still not resolved please do tell. I will then check at code level.

**Comment by nehalsanghvi** [comment]
1.1.2 is loading app in IE . Thank you so much for your quick fix. 

But I am still seeing the few warning in all browser do you know why?
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <th>. See https://fb.me/react-warning-keys for more information.
    in Unknown
    in Unknown (at TableGrid.js:42)
    in tbody (at TableGrid.js:41)
    in table (at TableGrid.js:40)
    in div (at TableGrid.js:39)
    in div (at TableGrid.js:38)
    in Unknown
    in div
    in Unknown (at TableGridContainer.js:12)
    in div (at TableGridContainer.js:10)
    in div
    in Unknown
    in Unknown (at TableGridContainer.js:9)
    in Unknown (at App.js:64)
    in div (at App.js:62)
    in div (at App.js:61)
    in div (at App.js:60)
    in div (at App.js:48)
    in Unknown (at App.js:47)
    in Unknown (created by Connect(Component))
    in Connect(Component) (at index.js:26)
    in Unknown (at index.js:25)

**Comment by LTPrashant** [comment]
I will have a look at it whenever I am free

**Comment by nehalsanghvi** [comment]
Hi Found the solution for the warning
the <th> array map does not have the key value added. Please can you update it?

**Comment by cheekujha** [comment]
Hey I am a little busy, could you please raise a pull request with changes and I will merge it.

**Comment by nehalsanghvi** [comment]
Hi I have committed the fix to nehalsanghvi-patch-1  branch. 
I was not able to test. But please merge the changes if you think this is the right fix.

**Comment by cheekujha** [comment]
you need to make a PULL REQUEST for me to be able to merge

**Comment by nehalsanghvi** [comment]
I have requested a pull
https://github.com/cheekujha/react-table-filter/pull/14

**Comment by nehalsanghvi** [comment]
Will these warning show in production environment ?

**Comment by cheekujha** [comment]
Merged the pull request and deployed version 1.1.3. Warnings will go away in this version
