### ISSUE TITLE
react-table-v6 + react-table-filter

### ISSUE THREAD

**Issue by AdamCyffka** [cheekujha/react-table-filter#39]
I'm trying to integrate react-table-filter with react-table-v6.

the goal is to give all the column data to rows in <TableFilter>, but I can't send it only the column, every time it send all of the table. I may have other errors (for the filter) because I can't test it yet.

Here is my code:
```javascript
import React, { Component } from "react";
import ReactTable from "react-table-v6";
import TableFilter from 'react-table-filter';

export default class Table extends Component {
  constructor(props) {
    super(props)

    this.state = {
      data: [],
    };

    this.columns = [
      {
        accessor: "id",
        Header: "Id",
      },
      {
        accessor: "age",
        Header: "Age",
        filterMethod: (filter, row) => {
          return row[filter.id] === filter.value;
        },
        Filter: ({ }) =>
          this.customFilter({ fieldName: 'age' })
      },
    ]
  }

  customFilter = ({ fieldName }) => {
    return (
      <TableFilter
        rows={this.state.data}
        onFilterUpdate={this.filterUpdated}
      >
        {this.state.data
          .map(item => item[fieldName])
  
          .filter((item, i, s) => s.lastIndexOf(item) === i)
          .map(function (value) {
            if (value === null)
              return;
            else {
              return (
                <th filterkey={value}>
                  {value}
                </th>
              );
            }
          })}
      </TableFilter>
    );
  }

  filterUpdated = (newData, filterConfiguration) => {
    this.setState({
      "data": newData
    });
  }

  componentDidMount() {
    UserService.getData()
    .then(response => {
      this.setState({
        data: response.data, // all data are store here
      })
    })
    .catch((err) => console.error(err))
  }

  render() {
    return (
      <div>
        <ReactTable
          data={this.state.data}
          filterable
          columns={this.columns}
          pageSizeOptions={[10, 30, 50, 100]}
          className="-striped -highlight"
          defaultPageSize={10}
        />
      </div>
    )
  }
}
```

**Comment by pjha-protonn** [comment]
Hey @AdamCyffka , will get back to you in this, let me take a look.

**Comment by Neo7252** [comment]
I also tried with the given example, but as soon as I change the data locally and use the API data, the data is there but the filters disappear.

**Comment by pjha-protonn** [comment]
Hey @AdamCyffka , i checked what you are trying to do. I don't think we can use it the way described above. You are trying to add TableFilter at a column level. Table filter is supposed to wrap the Headers of the Table.

Answering your other query.
```
I also tried with the given example, but as soon as I change the data locally and 
use the API data, the data is there but the filters disappear.
```
The initial data in react table filter is passed as empty hence you are not seeing the filters. If you are using API for loading the data, either don't render the TableFilter component till that data is loaded, or you can use the below mentioned instructions given on npm screen to reset the data for filter. Then it will work properly.

<img width="822" alt="Screenshot 2021-07-24 at 7 32 39 PM" src="https://user-images.githubusercontent.com/80766140/126870844-c7341c87-06ec-4058-839f-5f3784b6f92d.png">

Let me know if you need any more help

**Comment by Neo7252** [comment]
> Hey @AdamCyffka , i checked what you are trying to do. I don't think we can use it the way described above. You are trying to add TableFilter at a column level. Table filter is supposed to wrap the Headers of the Table.
> 
> Answering your other query.
> 
> ```
> I also tried with the given example, but as soon as I change the data locally and 
> use the API data, the data is there but the filters disappear.
> ```
> 
> The initial data in react table filter is passed as empty hence you are not seeing the filters. If you are using API for loading the data, either don't render the TableFilter component till that data is loaded, or you can use the below mentioned instructions given on npm screen to reset the data for filter. Then it will work properly.
> 
> <img alt="Screenshot 2021-07-24 at 7 32 39 PM" width="822" src="https://user-images.githubusercontent.com/80766140/126870844-c7341c87-06ec-4058-839f-5f3784b6f92d.png">
> 
> Let me know if you need any more help

Thanks, It's working now :)
